server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: echo-app
          predicates:
            - Path=/gateway/eureka/echo
          uri: lb://echo-app:8082
          filters:
            - RewritePath=/gateway/eureka/echo, /echo
        - id: echo-app
          predicates:
            - Path=/new/eureka/echo
          uri: lb://new-id:8082
          filters:
            - RewritePath=/new/eureka/echo, /echo
